// مراجعة Claude للمرشّحين قبل النشر التلقائي.
// Claude لا يخترع معلومات: يراجع سؤالًا مبنيًا على حقيقة من مصدر (Wikidata) ويحكم:
//   approve: صحيح وواضح ومناسب ← يُنشر
//   fix:     الحقيقة صحيحة لكن الصياغة/التسمية العربية تحتاج تصحيحًا (مثل «واشنطن العاصمة» ← «واشنطن»)
//   reject:  خطأ، غامض، أكثر من إجابة، غير مناسب، أو الصورة لا تُظهر الشيء بوضوح
// بلا "server-only": دوال القرار نقية ومختبرة؛ العميل يُمرَّر كمعامل.
import type Anthropic from "@anthropic-ai/sdk";
import { betaZodOutputFormat } from "@anthropic-ai/sdk/helpers/beta/zod";
import { z } from "zod";
import { hasHardFailure, runCandidateChecks, type CheckContext, type CheckResult } from "../checks";
import type { CandidatePayload } from "../types";

export const AI_REVIEW_MODEL = "claude-opus-5-5";
/** صور كثيرة في طلب واحد تبطئه وتكلّف أكثر */
const TEXT_BATCH = 25;
const IMAGE_BATCH = 8;

const ReviewSchema = z.object({
  reviews: z.array(
    z.object({
      id: z.string(),
      verdict: z.enum(["approve", "fix", "reject"]),
      reason: z.string(),
      fixed_question: z.string().nullable(),
      fixed_answer: z.string().nullable(),
      family_safe: z.boolean(),
    }),
  ),
});
export type AiReview = z.infer<typeof ReviewSchema>["reviews"][number];

export interface ReviewItem {
  id: string;
  payload: CandidatePayload;
  fact: { subject: string; predicate: string; object_value: string; source_url: string | null } | null;
}

// ثابت تمامًا (بدون تواريخ أو معرّفات) ليبقى قابلًا للتخزين المؤقت
const SYSTEM = `You are the final quality gate for "Hayra" (حيرة), an Arabic family trivia game played by Arab families and friends.
Each item is a question that was generated by a fixed template from a structured fact (usually Wikidata). Questions you approve go live in the game immediately, with no human review, so be strict.

For each item decide:
- "approve": the answer is correct according to both the source fact and your own knowledge; the question has exactly one correct answer; the Arabic is natural and correctly spelled; the answer uses the name Arab players commonly use; it is suitable for a general Arab family audience.
- "fix": the underlying fact is correct, but the Arabic wording or the answer's Arabic name should change (e.g. "واشنطن العاصمة" → "واشنطن", an obscure transliteration → the common Arabic name, awkward phrasing). Put the corrected text in fixed_question and/or fixed_answer (null for any field you keep). Never change which fact is being asked about.
- "reject": the answer is wrong or outdated, the question is ambiguous or has several valid answers, the subject is too obscure to be fun, the content is religiously/politically sensitive or culturally inappropriate, or (for image items) the image does not clearly show the subject, shows text that reveals the answer, or is unsuitable for families.

Rules:
- Judge each item independently. Do not invent facts beyond verifying the given one.
- For multiple_choice items, the answer must be one of the choices and exactly one choice may be correct.
- family_safe = false if the content or image is unsuitable for young children, even when you approve.
- Write "reason" in Arabic, one short sentence.
- Return exactly one review per item, using the item's id.`;

function itemText(it: ReviewItem): string {
  const p = it.payload;
  return JSON.stringify({
    id: it.id,
    type: p.type,
    category: `${p.category}/${p.subcategory ?? ""}`,
    question: p.question_text,
    answer: p.answer,
    choices: p.choices ?? null,
    has_image: !!p.image_url,
    source_fact: it.fact ? { subject: it.fact.subject, relation: it.fact.predicate, value: it.fact.object_value, url: it.fact.source_url } : null,
  });
}

async function reviewBatch(client: Anthropic, items: ReviewItem[]): Promise<AiReview[]> {
  const content: Anthropic.Beta.BetaContentBlockParam[] = [{ type: "text", text: `Review these ${items.length} items:` }];
  for (const it of items) {
    content.push({ type: "text", text: itemText(it) });
    if (it.payload.image_url) {
      content.push({ type: "text", text: `Image for item ${it.id}:` });
      content.push({ type: "image", source: { type: "url", url: it.payload.image_url } });
    }
  }
  const res = await client.beta.messages.parse({
    model: AI_REVIEW_MODEL,
    max_tokens: 16000,
    betas: ["server-side-fallback-2026-07-01"],
    fallbacks: "default",
    system: SYSTEM,
    output_config: { effort: "medium", format: betaZodOutputFormat(ReviewSchema) },
    messages: [{ role: "user", content }],
  });
  // رفض أو انقطاع ← لا مراجعة (يبقى المرشّح للمراجعة البشرية، لا يُنشر)
  if (res.stop_reason === "refusal" || res.stop_reason === "max_tokens" || !res.parsed_output) return [];
  const ids = new Set(items.map((i) => i.id));
  return res.parsed_output.reviews.filter((r) => ids.has(r.id));
}

/**
 * أخطاء لن تُحل بإعادة المحاولة داخل نفس التشغيل: رصيد منتهٍ/طلب خاطئ (400)، مفتاح خاطئ (401)،
 * لا صلاحية (403)، نموذج غير موجود (404). 429 و5xx والشبكة يعيدها الـSDK تلقائيًا (maxRetries).
 */
export function isFatalAiError(e: unknown): boolean {
  const status = (e as { status?: unknown })?.status;
  return typeof status === "number" && [400, 401, 403, 404].includes(status);
}

export interface ReviewRunResult {
  reviews: Map<string, AiReview>;
  /** عناصر لم تحصل على مراجعة (خطأ، رفض، انقطاع، أو توقف بعد خطأ قاتل) */
  failed: number;
  /** أول خطأ قاتل — توقفت بعده كل الدفعات */
  fatalError: string | null;
}

/**
 * يراجع كل العناصر على دفعات. خطأ عابر في دفعة لا يوقف الباقي،
 * أما الخطأ القاتل فيوقف كل شيء فورًا. العنصر بلا مراجعة لا يُنشر أبدًا.
 */
export async function reviewWithClaude(client: Anthropic, items: ReviewItem[], log: (msg: string) => void = () => {}): Promise<ReviewRunResult> {
  const reviews = new Map<string, AiReview>();
  const withImg = items.filter((i) => i.payload.image_url);
  const textOnly = items.filter((i) => !i.payload.image_url);
  const batches: ReviewItem[][] = [];
  for (let i = 0; i < textOnly.length; i += TEXT_BATCH) batches.push(textOnly.slice(i, i + TEXT_BATCH));
  for (let i = 0; i < withImg.length; i += IMAGE_BATCH) batches.push(withImg.slice(i, i + IMAGE_BATCH));
  let fatalError: string | null = null;
  for (const b of batches) {
    try {
      const got = await reviewBatch(client, b);
      if (got.length < b.length) log(`ai_review: ${b.length - got.length}/${b.length} items without a review (refusal/truncation/missing ids)`);
      for (const r of got) reviews.set(r.id, r);
    } catch (e) {
      log(`ai_review batch failed (${b.length} items): ${(e as Error).message}`);
      if (isFatalAiError(e)) {
        fatalError = (e as Error).message;
        break;
      }
    }
  }
  return { reviews, failed: items.length - reviews.size, fatalError };
}

/** هل ما زال المرشّح ينتظر مراجعة Claude؟ (لا يوجد حكم فعلي approve/fix/reject في أي سطر ai_review) */
export function needsAiReview(checks: { check_name: string; status: string; details?: Record<string, unknown> | null }[]): boolean {
  if (checks.some((k) => k.status === "fail")) return false;
  if (!checks.some((k) => k.check_name === "duplicate" && k.status === "pass")) return false;
  return !checks.some((k) => k.check_name === "ai_review" && typeof k.details?.verdict === "string");
}

// ------------------------------------------------------------------ القرار (دوال نقية)

export type AiDecision =
  | { action: "publish"; payload: CandidatePayload; check: CheckResult }
  | { action: "hold"; check: CheckResult }
  | { action: "reject"; reason: string; check: CheckResult };

const ARABIC = /[ء-ي]/;

/**
 * يحوّل حكم Claude إلى قرار. «fix» يُطبَّق ثم تُعاد الفحوص الثابتة على النص الجديد:
 * إن نجحت يُنشر (مع وسم ai-fixed)، وإلا يبقى للمراجعة. بدون مراجعة ← hold (لا نشر أبدًا بلا Claude).
 */
export function decideAfterReview(payload: CandidatePayload, review: AiReview | undefined, ctx: CheckContext): AiDecision {
  if (!review) return { action: "hold", check: { check_name: "ai_review", status: "warning", details: { reason: "لا توجد مراجعة من Claude (فشل/رفض/لم تُرسل)" } } };
  const base = { model: AI_REVIEW_MODEL, verdict: review.verdict, reason: review.reason, family_safe: review.family_safe };

  if (review.verdict === "reject") return { action: "reject", reason: `ai_review: ${review.reason}`, check: { check_name: "ai_review", status: "fail", details: base } };

  let next: CandidatePayload = { ...payload, family_safe: payload.family_safe !== false && review.family_safe };
  if (review.verdict === "fix") {
    const q = review.fixed_question?.trim() || null;
    const a = review.fixed_answer?.trim() || null;
    if ((!q && !a) || (q && !ARABIC.test(q))) return { action: "hold", check: { check_name: "ai_review", status: "warning", details: { ...base, note: "اقتراح تصحيح غير صالح" } } };
    next = { ...next, question_text: q ?? next.question_text, answer: a ?? next.answer, tags: [...(next.tags ?? []), "ai-fixed"] };
    // اختيارات: الإجابة المصححة يجب أن تبقى ضمن الاختيارات
    if (next.type === "multiple_choice" && next.choices && a && !next.choices.includes(a)) {
      next = { ...next, choices: next.choices.map((c) => (c === payload.answer ? a : c)) };
    }
    const recheck = runCandidateChecks(next, ctx);
    const fixDetails = { ...base, original: { question: payload.question_text, answer: payload.answer }, fixed: { question: next.question_text, answer: next.answer } };
    if (hasHardFailure(recheck))
      return { action: "hold", check: { check_name: "ai_review", status: "warning", details: { ...fixDetails, note: "التصحيح لم ينجح في الفحوص الثابتة", failed: recheck.filter((r) => r.status === "fail").map((r) => r.check_name) } } };
    return { action: "publish", payload: next, check: { check_name: "ai_review", status: "warning", details: { ...fixDetails, applied: true } } };
  }
  return { action: "publish", payload: next, check: { check_name: "ai_review", status: "pass", details: base } };
}
