-- =====================================================================
-- حيرة | HAYRA — 004: الفئات والفئات الفرعية والباقات الجاهزة
-- =====================================================================

insert into public.categories (slug, name, icon, color, is_interactive, description, sort_order) values
  ('islamic', 'الإسلاميات', '🕌', 'leaf', false, 'القرآن والسيرة والصحابة والفقه والتاريخ الإسلامي', 1),
  ('sports', 'الرياضة', '⚽', 'volt', false, 'كرة القدم وكأس العالم والأندية والرياضات الأخرى', 2),
  ('drama', 'دراما وسينما', '🎬', 'wine', false, 'الدراما العربية والأفلام والممثلون والكرتون', 3),
  ('brands', 'براندات', '🏷️', 'ember', false, 'الشعارات والسيارات والمطاعم والشركات والأزياء والساعات', 4),
  ('geography', 'جغرافيا', '🌍', 'volt', false, 'الدول والعواصم والأعلام والأنهار والجبال والمعالم', 5),
  ('history', 'تاريخ', '🏛️', 'wine', false, 'الحضارات والمعارك والتاريخ العربي والحديث', 6),
  ('science', 'علوم', '🔬', 'violet', false, 'الفضاء وجسم الإنسان والحيوانات والتكنولوجيا', 7),
  ('arabic', 'لغة عربية', '📜', 'gold', false, 'النحو والكلمات والمعاني والأمثال والشعر', 8),
  ('puzzles', 'ألغاز وذكاء', '🧩', 'violet', false, 'ألغاز وأسئلة ذكاء وتفكير', 9),
  ('general', 'معلومات عامة', '💡', 'gold', false, 'معلومات منوعة من كل مكان', 10),
  ('interactive', 'تحديات تفاعلية', '🎭', 'ember', true, 'من أنا؟ مثّلها، ارسم، صوت، كلمة سرية وتحديات QR', 11)
on conflict (slug) do nothing;

insert into public.subcategories (category_id, slug, name, icon, sort_order)
select c.id, v.slug, v.name, v.icon, v.sort_order
from (values
  ('islamic', 'quran', 'القرآن الكريم', '📖', 1),
  ('islamic', 'quran-sciences', 'علوم القرآن', '📜', 2),
  ('islamic', 'seerah', 'السيرة النبوية', '🌙', 3),
  ('islamic', 'prophets', 'الأنبياء', '✨', 4),
  ('islamic', 'sahaba', 'الصحابة', '🛡️', 5),
  ('islamic', 'sahabiyat', 'الصحابيات', '🌸', 6),
  ('islamic', 'mothers-believers', 'أمهات المؤمنين', '💐', 7),
  ('islamic', 'rashidun', 'الخلفاء الراشدون', '👑', 8),
  ('islamic', 'ghazawat', 'الغزوات', '⚔️', 9),
  ('islamic', 'hadith', 'الحديث النبوي', '📚', 10),
  ('islamic', 'islamic-history', 'التاريخ الإسلامي', '🏰', 11),
  ('islamic', 'muslim-scholars', 'علماء المسلمين', '🎓', 12),
  ('islamic', 'mosques', 'المساجد والمعالم الإسلامية', '🕋', 13),
  ('islamic', 'fiqh', 'الفقه والعبادات', '🤲', 14),
  ('islamic', 'hajj', 'الحج والعمرة', '🕋', 15),
  ('islamic', 'ramadan', 'رمضان', '🏮', 16),
  ('islamic', 'adhkar', 'الأذكار والأدعية', '📿', 17),
  ('sports', 'football', 'كرة القدم', '⚽', 1),
  ('sports', 'world-cup', 'كأس العالم', '🏆', 2),
  ('sports', 'ucl', 'دوري أبطال أوروبا', '⭐', 3),
  ('sports', 'leagues', 'الدوريات', '🏟️', 4),
  ('sports', 'clubs', 'الأندية', '🛡️', 5),
  ('sports', 'players', 'اللاعبون', '👟', 6),
  ('sports', 'coaches', 'المدربون', '📋', 7),
  ('sports', 'national-teams', 'المنتخبات', '🚩', 8),
  ('sports', 'general-sports', 'رياضة عامة', '🏅', 9),
  ('drama', 'syrian-drama', 'دراما سورية', '🎭', 1),
  ('drama', 'egyptian-drama', 'دراما مصرية', '🎞️', 2),
  ('drama', 'gulf-drama', 'دراما خليجية', '🌴', 3),
  ('drama', 'arabic-series', 'مسلسلات عربية', '📺', 4),
  ('drama', 'movies', 'أفلام', '🎬', 5),
  ('drama', 'actors', 'ممثلون', '🌟', 6),
  ('drama', 'characters', 'شخصيات', '🎩', 7),
  ('drama', 'cartoon', 'كرتون', '🧸', 8),
  ('drama', 'anime', 'أنمي', '🗾', 9),
  ('brands', 'brands-general', 'براندات عامة', '🏷️', 1),
  ('brands', 'logos', 'شعارات', '🔰', 2),
  ('brands', 'cars', 'سيارات', '🚗', 3),
  ('brands', 'restaurants', 'مطاعم', '🍔', 4),
  ('brands', 'tech-companies', 'شركات تقنية', '💻', 5),
  ('brands', 'fashion', 'أزياء', '👗', 6),
  ('brands', 'watches', 'ساعات', '⌚', 7),
  ('geography', 'capitals', 'عواصم', '🏙️', 1),
  ('geography', 'countries', 'دول', '🗺️', 2),
  ('geography', 'flags', 'أعلام', '🚩', 3),
  ('geography', 'maps', 'خرائط', '🧭', 4),
  ('geography', 'rivers', 'أنهار', '🌊', 5),
  ('geography', 'mountains', 'جبال', '⛰️', 6),
  ('geography', 'seas', 'بحار ومحيطات', '🌊', 7),
  ('geography', 'landmarks', 'معالم', '🗼', 8),
  ('history', 'ancient', 'تاريخ قديم وحضارات', '🏺', 1),
  ('history', 'arab-history', 'التاريخ العربي', '🐎', 2),
  ('history', 'modern-history', 'تاريخ حديث', '📰', 3),
  ('history', 'battles', 'حروب ومعارك', '⚔️', 4),
  ('history', 'jordan-history', 'تاريخ الأردن', '🇯🇴', 5),
  ('science', 'general-science', 'علوم عامة', '🧪', 1),
  ('science', 'space', 'فضاء', '🪐', 2),
  ('science', 'human-body', 'جسم الإنسان', '🫀', 3),
  ('science', 'animals', 'حيوانات', '🦁', 4),
  ('science', 'technology', 'تكنولوجيا', '📡', 5),
  ('science', 'chemistry', 'كيمياء', '⚗️', 6),
  ('science', 'physics', 'فيزياء', '🧲', 7),
  ('arabic', 'grammar', 'لغة ونحو', '✒️', 1),
  ('arabic', 'meanings', 'كلمات ومعاني', '🔤', 2),
  ('arabic', 'proverbs', 'أمثال', '💬', 3),
  ('arabic', 'poetry', 'شعر', '🪶', 4),
  ('puzzles', 'riddles', 'ألغاز', '❔', 1),
  ('puzzles', 'iq', 'ذكاء', '🧠', 2),
  ('puzzles', 'math-mind', 'رياضيات ذهنية', '🔢', 3),
  ('general', 'trivia', 'منوعات', '💡', 1),
  ('general', 'records', 'أرقام قياسية', '📏', 2),
  ('general', 'inventions', 'اختراعات', '⚙️', 3),
  ('interactive', 'who-am-i', 'من أنا؟', '🕵️', 1),
  ('interactive', 'guess-image', 'خمن الصورة', '🖼️', 2),
  ('interactive', 'guess-logo', 'خمن الشعار', '🔰', 3),
  ('interactive', 'sound', 'صوت', '🎧', 4),
  ('interactive', 'qr-acting', 'مثّلها', '🎭', 5),
  ('interactive', 'qr-drawing', 'ارسم وخمّن', '🎨', 6),
  ('interactive', 'qr-describe', 'وصف بدون الكلمة', '🗣️', 7),
  ('interactive', 'qr-secret', 'كلمة سرية', '🤫', 8),
  ('interactive', 'qr-who-am-i', 'مين أنا؟ (QR)', '🎩', 9),
  ('interactive', 'qr-sound', 'صوت فقط', '🔊', 10),
  ('interactive', 'qr-movement', 'تحدي حركة', '🤸', 11)
) as v(cat, slug, name, icon, sort_order)
join public.categories c on c.slug = v.cat
on conflict (category_id, slug) do nothing;

insert into public.game_packs (slug, name, emoji, description, level, category_count, question_types, family_mode, is_seasonal, season_label, sort_order) values
  ('family-night', 'جلسة عائلية', '👨‍👩‍👧‍👦', 'منوعة وخفيفة تناسب كل أفراد العائلة', 'family', 6, '{}', true, false, null, 1),
  ('deep-islamic', 'إسلاميات عميقة', '🕌', 'للمحترفين في السيرة والصحابة وعلوم القرآن', 'pro', 6, '{}', true, false, null, 2),
  ('football', 'كرة القدم', '⚽', 'كأس العالم والأندية واللاعبين والمدربين', 'medium', 5, '{}', false, false, null, 3),
  ('ramadan', 'رمضان', '🏮', 'أجواء رمضانية: قرآن وسيرة وأذكار ودراما', 'medium', 6, '{}', true, true, 'رمضان', 4),
  ('arab-drama', 'دراما عربية', '🎭', 'سوري ومصري وخليجي وأفلام وكرتون زمان', 'medium', 5, '{}', false, false, null, 5),
  ('friends-challenge', 'تحدي الأصدقاء', '🔥', 'ألغاز وتمثيل ورسم وتحديات QR', 'medium', 6, '{}', false, false, null, 6),
  ('eid', 'العيد', '🎉', 'جلسة العيد الخفيفة للعائلة', 'family', 5, '{}', true, true, 'العيد', 7),
  ('world-cup', 'كأس العالم', '🏆', 'كل ما يخص المونديال', 'medium', 4, '{}', false, true, 'كأس العالم', 8)
on conflict (slug) do nothing;

insert into public.game_pack_categories (pack_id, category_id, subcategory_id, sort_order)
select p.id, c.id, sc.id, v.ord
from (values
  ('family-night', 'islamic', null, 1),
  ('family-night', 'sports', null, 2),
  ('family-night', 'drama', null, 3),
  ('family-night', 'puzzles', null, 4),
  ('family-night', 'geography', null, 5),
  ('family-night', 'general', null, 6),
  ('deep-islamic', 'islamic', 'quran', 1),
  ('deep-islamic', 'islamic', 'seerah', 2),
  ('deep-islamic', 'islamic', 'sahaba', 3),
  ('deep-islamic', 'islamic', 'quran-sciences', 4),
  ('deep-islamic', 'islamic', 'ghazawat', 5),
  ('deep-islamic', 'islamic', 'hadith', 6),
  ('deep-islamic', 'islamic', 'mothers-believers', 7),
  ('deep-islamic', 'islamic', 'muslim-scholars', 8),
  ('football', 'sports', 'world-cup', 1),
  ('football', 'sports', 'ucl', 2),
  ('football', 'sports', 'players', 3),
  ('football', 'sports', 'coaches', 4),
  ('football', 'sports', 'national-teams', 5),
  ('football', 'sports', 'football', 6),
  ('football', 'sports', 'clubs', 7),
  ('ramadan', 'islamic', 'ramadan', 1),
  ('ramadan', 'islamic', 'quran', 2),
  ('ramadan', 'islamic', 'seerah', 3),
  ('ramadan', 'islamic', 'adhkar', 4),
  ('ramadan', 'drama', null, 5),
  ('ramadan', 'puzzles', null, 6),
  ('arab-drama', 'drama', 'syrian-drama', 1),
  ('arab-drama', 'drama', 'egyptian-drama', 2),
  ('arab-drama', 'drama', 'gulf-drama', 3),
  ('arab-drama', 'drama', 'movies', 4),
  ('arab-drama', 'drama', 'cartoon', 5),
  ('arab-drama', 'drama', 'anime', 6),
  ('friends-challenge', 'puzzles', null, 1),
  ('friends-challenge', 'interactive', 'qr-acting', 2),
  ('friends-challenge', 'interactive', 'qr-drawing', 3),
  ('friends-challenge', 'interactive', 'qr-describe', 4),
  ('friends-challenge', 'interactive', 'who-am-i', 5),
  ('friends-challenge', 'general', null, 6),
  ('friends-challenge', 'brands', null, 7),
  ('eid', 'general', null, 1),
  ('eid', 'puzzles', null, 2),
  ('eid', 'interactive', 'qr-acting', 3),
  ('eid', 'geography', null, 4),
  ('eid', 'islamic', null, 5),
  ('world-cup', 'sports', 'world-cup', 1),
  ('world-cup', 'sports', 'national-teams', 2),
  ('world-cup', 'sports', 'players', 3),
  ('world-cup', 'geography', 'flags', 4)
) as v(pack, cat, sub, ord)
join public.game_packs p on p.slug = v.pack
join public.categories c on c.slug = v.cat
left join public.subcategories sc on sc.category_id = c.id and sc.slug = v.sub
where not exists (select 1 from public.game_pack_categories x where x.pack_id = p.id);
